import math

# FRONT RADAR: a cone
FRADAR_HALF_ANGLE = 60
FRADAR_FULL_ANGLE = FRADAR_HALF_ANGLE * 2
FRADAR_RADIUS = 40

# SURROUNDING RADAR: a sphere
SRADAR_RADIUS = 10

# VEHICLE DIMENSIONS
VEH_LENGTH = 16
VEH_WIDTH = 12